name: Release

on:
  push:
    tags:
      - v*

jobs:
  release_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint
        run: cargo clippy --tests -- --deny warnings
      - name: Release build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/release/chug
